baseURL = "www.example.com"
languageCode = "en-us"
title = "Elizabethtown-Lewis Emergency Squad"
theme = "hugo-hero-theme-master"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Elizabethtown-Lewis Emergency Squad."
    meta_og_title = "Elizabethtown-Lewis Emergency Squad"
    meta_og_type = "website"
    meta_og_url = "etownlewisems.org"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Good EMS doesn't happen by accident."


[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
