baseurl = "/"
title = "Elizabethtown-Lewis Emergency Squad"
author = "Daniel Zaragoza (Danielkvist)"
googleAnalytics = ""
defaultContentLanguage = "en"
paginate = 3

theme = "terrassa"


[params]
    description = "Terrassa is a simple, fast and responsive theme for Hugo with a strong focus on accessibility made from scratch."
    favicon = "favicon.ico"
    logo = ""

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "Contact"
    link = "contact" # Relative URL

[params.separator] # Separators between sections on the home page
    show = false

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.form] # Contact form
    netlify = true
    action = "https://formspree.io/your@email.com"
    method = "POST"
    inputNameName = "name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your name"
    inputEmailName = "email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your email"
    inputMsgName = "message"
    inputMsgLabel = "Write something"
    inputMsgLength = 750
    inputSubmitValue = "Send"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.contact] # Contact info
    email = "etownlewisems@gmail.com"
    address = "986875976 US Route 9, Lewis NY 12950"

[params.social]
    twitter = "https://twitter.com/john"
    instagram = "https://instagram.com/john"

[params.copy] # Copyright
    copy = "2020 Elizabethtown-Lewis EMS" # Empty for default content

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = false
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = false
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = false
        simple = false
    [privacy.youtube]
        disable = false
        privacyEnhanced = true

[params.languageSwitcher]
    show = true

